apiVersion: v1
kind: Service
metadata:
  name: alpha
  namespace: {{ .Release.Namespace }}
  labels:
    app: alpha
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    app: alpha
