apiVersion: v1
kind: Service
metadata:
  name: beta
  namespace: {{ .Release.Namespace }}
  labels:
    app: beta
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8081
  selector:
    app: beta
