
# only need to create this f we have muliple versions that we want to canary...
{{if gt (len .Values.images) 1 }}
---
# need to define a destinationrule to define the different subsets of the service
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: beta
spec:
  host: beta.default.svc.cluster.local
  subsets:
  {{- range .Values.images }}
  - name: "{{ .tag }}"
    labels:
      version: "{{ .tag }}"
  {{- end}}
---
# the virtual service defines routing for the service
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: beta
spec:
  hosts:
    - beta.default.svc.cluster.local
  http:
  - route:
  {{- range .Values.images }}
    - destination:
        host: beta.default.svc.cluster.local
        subset: "{{ .tag }}"
      weight: {{ .weight }}
  {{- end}}
{{- end}}
